// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWB12izLC2d84yWi2q22PZCDFwgSsRFsU',
    appId: '1:361137060318:web:4141da7b7bc65fc237454f',
    messagingSenderId: '361137060318',
    projectId: 'copsandrobbers-c2281',
    authDomain: 'copsandrobbers-c2281.firebaseapp.com',
    storageBucket: 'copsandrobbers-c2281.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqXgByFZfTJAwK4Zw3385hVyh3pugdSzs',
    appId: '1:361137060318:android:828ad5f499a5cb5837454f',
    messagingSenderId: '361137060318',
    projectId: 'copsandrobbers-c2281',
    storageBucket: 'copsandrobbers-c2281.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBvXRxCUOcXZk2OZgSpBXcf-40IUNc-E',
    appId: '1:361137060318:ios:e052218cb5107d7f37454f',
    messagingSenderId: '361137060318',
    projectId: 'copsandrobbers-c2281',
    storageBucket: 'copsandrobbers-c2281.firebasestorage.app',
    iosBundleId: 'com.elipair.copsandrobbers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBvXRxCUOcXZk2OZgSpBXcf-40IUNc-E',
    appId: '1:361137060318:ios:0b81e13d43d595da37454f',
    messagingSenderId: '361137060318',
    projectId: 'copsandrobbers-c2281',
    storageBucket: 'copsandrobbers-c2281.firebasestorage.app',
    iosBundleId: 'com.example.copsAndRobbers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWB12izLC2d84yWi2q22PZCDFwgSsRFsU',
    appId: '1:361137060318:web:81e069bdf1f7270f37454f',
    messagingSenderId: '361137060318',
    projectId: 'copsandrobbers-c2281',
    authDomain: 'copsandrobbers-c2281.firebaseapp.com',
    storageBucket: 'copsandrobbers-c2281.firebasestorage.app',
  );
}
